version: '3'
services:
  nx_php:
    build: ./php
    container_name: nx_php
    volumes:
      - ./source:/var/www/html
    links:
      - nx_memcached
      - nx_redis
      - nx_mysql
    environment:
      - DEBUG=1
    ports:
      - 80:80
  nx_memcached:
    image: memcached:alpine
    container_name: nx_memcached
    command: 'memcached -m 512m'
  nx_redis:
    image: redis:alpine
    container_name: nx_redis
  nx_mysql:
    image: mysql
    container_name: nx_mysql
    volumes:
      - vol_mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  nx_node:
    build: node:slim
    command: 'npm start'
    working_dir: '/var/www/html'
    container_name: nx_node
    expose:
      - "8888"
    volumes_from:
      - nx_php
volumes:
  vol_mysql:
    driver: "local"
